version: 2.1
jobs:
  build:
    docker:
      - image: amd64/centos:7
    environment:
      CC: /usr/bin/clang
      BASH_ENV: /etc/profile.d/nextspace.sh
    steps:
      - run:
          name: Setup Yum
          command: |
            yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            yum -y update
      - run:
          name: Install dependencies
          command: |
            yum -y install git
            yum -y install libffi libffi-devel
            yum -y install libxml2 libxml2-devel
            yum -y install gnutls gnutls-devel
            yum -y install libxslt libxslt-devel
            yum -y install libicu libicu-devel
            yum -y install libjpeg libjpeg-devel
            yum -y install libtiff libtiff-devel
            yum -y install libpng libpng-devel
            yum -y install freetype freetype-devel
            yum -y install libart_lgpl libart_lgpl-devel
            yum -y install libX11 libX11-devel
            yum -y install libXt libXt-devel
            yum -y install which
            yum -y groupinstall "X Window System"
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/clang-libs-7.0.1-4.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/clang-7.0.1-4.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/libdispatch-1.3.1121-3.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/libdispatch-devel-1.3.1121-3.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/libobjc2-2.0-3.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/libobjc2-devel-2.0-3.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/llvm-libs-7.0.1-3.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-gnustep-1.26.0_0.25.0-2.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-gnustep-devel-1.26.0_0.25.0-2.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-core-0.95-8.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-core-devel-0.95-8.el7.x86_64.rpm
      - run:
          name: Build and install libs-base
          command: |
            git clone https://github.com/gnustep/libs-base
            cd libs-base
            ./configure --disable-mixedabi
            make
            make install
            ldconfig
      - run:
          name: Build and install libs-gui
          command: |
            git clone https://github.com/gnustep/libs-gui
            cd libs-gui
            git checkout nextspace
            ./configure
            make
            make install
            ldconfig
      - run:
          name: Build and install libs-back
          command: |
            git clone https://github.com/gnustep/libs-back
            cd libs-back
            git checkout nextspace
            ./configure --enable-graphics=art --with-name=art
            make
            make fonts=no install
            ldconfig
      - checkout:
          path: /root/nextspace
      - run:
          name: Build and install Frameworks
          command: |
            cd /root/nextspace/Frameworks
            yum -y install `grep "BuildRequires" nextspace-frameworks.spec | awk -c '{print $2}'`
            make
            make install
            ldconfig
      - run:
          name: Build and install Applications
          command: |
            cd /root/nextspace/Libraries/libwraster
            make 
            make install
            cd /root/nextspace/Applications
            make 
            cd Applications
            yum -y install `grep "BuildRequires" nextspace-applications.spec | awk -c '{print $2}'`
            make
            make install
